apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - path: bootstrap-op.yaml
    target:
      kind: Application
      name: bootstrap
  - path: appset-generator-op.yaml
    target:
      kind: Application
      name: appset-generator
