apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "{{ .Values.bootstrap.repoURL }}"
    targetRevision: "{{ .Values.bootstrap.targetRevision }}"
    path: bootstrap/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - AllowEmpty=true
    automated:
      prune: true
      selfHeal: true
