apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/imtpot/argocd-bootstrap
    targetRevision: HEAD
    path: charts/appset-generator
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - AllowEmpty=true
    automated:
      selfHeal: true
